# Состояния для диалогов (ConversationHandler)

WAITING_DATE_SINGLE = 1
WAITING_PERIOD_TYPE = 2
WAITING_PERIOD_START = 3
WAITING_PERIOD_END = 4
WAITING_ADD_MANAGER = 5
WAITING_REMOVE_MANAGER = 6
WAITING_MANAGER_PHONE = 7
WAITING_PERIOD_YEAR = 8
WAITING_PERIOD_MONTH = 9
WAITING_PERIOD_QUARTER = 10
WAITING_YEAR_SELECT = 11
WAITING_DYNAMICS_SELECT = 12
WAITING_DYNAMICS_RANGE_START = 13
WAITING_DYNAMICS_RANGE_END = 14

# Состояния для товарных отчётов
WAITING_PRODUCT_DATE = 20
WAITING_PRODUCT_PERIOD_TYPE = 21
WAITING_PRODUCT_PERIOD_START = 22
WAITING_PRODUCT_PERIOD_END = 23
WAITING_PRODUCT_YEAR = 24
WAITING_PRODUCT_MONTH = 25
WAITING_PRODUCT_QUARTER = 26
WAITING_PRODUCT_YEAR_SELECT = 27

# Состояния для динамики по товару
WAITING_PRODUCT_SELECT = 30
WAITING_PRODUCT_METRIC = 31
WAITING_PRODUCT_PERIOD_CHOICE = 32
WAITING_PRODUCT_SINGLE_YEAR = 33
WAITING_PRODUCT_RANGE_START = 34
WAITING_PRODUCT_RANGE_END = 35
WAITING_PRODUCT_SKU_MANUAL = 36  # устаревшее, не используется (ручной ввод SKU удалён)
